spring:
  application:
    name: sisyphus
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  devtools:
    livereload:
      enabled: true
springdoc:
  swagger-ui:
    path: /docs