spring:
  application:
    name: sisyphus
  datasource:
    url: jdbc:h2:./db/devel;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jooq:
    sql-dialect: h2
springdoc:
  swagger-ui:
    path: /docs